In [2]:
#from tensorflow.keras import layers
#from tensorflow.keras import models
import numpy as np 

In [3]:
import pandas as pd
dataframe = pd.read_csv("iris.data")
data = np.array(dataframe.values)
print(data.shape)

(149, 5)


In [4]:
X = data[:,:-1]
X = np.asarray(X.astype(np.float32))
y = data[:,-1]
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [5]:
from collections import Counter
counter = Counter()
counter.update(y)
print(counter)

Counter({'Iris-versicolor': 50, 'Iris-virginica': 50, 'Iris-setosa': 49})


In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print('Train:')
print(X_train.shape)
print(y_train.shape)
print('Test:')
print(X_test.shape)
print(y_test.shape)

Train:
(104, 4)
(104,)
Test:
(45, 4)
(45,)


In [8]:
print(X_train[:2])

[[5.8 2.7 3.9 1.2]
 [6.3 2.8 5.1 1.5]]


In [9]:
from sklearn.linear_model import LogisticRegression 

In [10]:
model = LogisticRegression()
model.fit(X_train,y_train)


LogisticRegression()

In [11]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.91      0.77      0.83        13
           2       0.80      0.92      0.86        13

    accuracy                           0.91        45
   macro avg       0.90      0.90      0.90        45
weighted avg       0.92      0.91      0.91        45



In [12]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(10), 
                      batch_size=10, activation='logistic',max_iter=100)
model.fit(X_train,y_train)  # training

/Users/macos/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='logistic', batch_size=10, hidden_layer_sizes=10,
              max_iter=100)

In [13]:
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.77      0.87        13
           2       0.81      1.00      0.90        13

    accuracy                           0.93        45
   macro avg       0.94      0.92      0.92        45
weighted avg       0.95      0.93      0.93        45



In [14]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
print(y_train[:2])

2023-12-30 15:04:15.164952: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[0. 1. 0.]
 [0. 0. 1.]]


In [15]:
from tensorflow.keras import layers
from tensorflow.keras import models

model = models.Sequential()
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', 
              metrics=['accuracy'])

In [16]:
model.fit(X_train,y_train,epochs=100, batch_size=10, verbose=2)

Epoch 1/100
11/11 - 1s - loss: 1.0798 - accuracy: 0.2981 - 705ms/epoch - 64ms/step
Epoch 2/100
11/11 - 0s - loss: 0.8795 - accuracy: 0.7308 - 14ms/epoch - 1ms/step
Epoch 3/100
11/11 - 0s - loss: 0.7894 - accuracy: 0.9038 - 15ms/epoch - 1ms/step
Epoch 4/100
11/11 - 0s - loss: 0.7320 - accuracy: 0.7212 - 15ms/epoch - 1ms/step
Epoch 5/100
11/11 - 0s - loss: 0.6878 - accuracy: 0.6635 - 15ms/epoch - 1ms/step
Epoch 6/100
11/11 - 0s - loss: 0.6492 - accuracy: 0.7788 - 14ms/epoch - 1ms/step
Epoch 7/100
11/11 - 0s - loss: 0.6127 - accuracy: 0.9038 - 14ms/epoch - 1ms/step
Epoch 8/100
11/11 - 0s - loss: 0.5835 - accuracy: 0.8269 - 15ms/epoch - 1ms/step
Epoch 9/100
11/11 - 0s - loss: 0.5601 - accuracy: 0.9135 - 14ms/epoch - 1ms/step
Epoch 10/100
11/11 - 0s - loss: 0.5280 - accuracy: 0.8942 - 14ms/epoch - 1ms/step
Epoch 11/100
11/11 - 0s - loss: 0.5037 - accuracy: 0.8365 - 13ms/epoch - 1ms/step
Epoch 12/100
11/11 - 0s - loss: 0.4806 - accuracy: 0.9519 - 15ms/epoch - 1ms/step
Epoch 13/100
11/11 - 0s

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                80        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 723 (2.82 KB)
Trainable params: 723 (2.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
y_pred = model.predict(X_test)
print(y_pred[:2])

2/2 [==============================] - 0s 2ms/step
[[8.3393027e-04 9.9684018e-01 2.3257991e-03]
 [9.9977446e-01 2.2546190e-04 1.8226350e-09]]


In [19]:
y_pred = y_pred.argmax(axis=1)
print(y_pred)
print(y_test)

[1 0 2 1 1 0 1 2 1 2 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

