In [1]:
import pandas as pd 
import numpy as np 

In [2]:
filename = 'Real estate valuation data set.xlsx'
xl = pd.ExcelFile(filename)
sheet_names = xl.sheet_names
df = xl.parse(sheet_names[0])
df.head(5)

FileNotFoundError: [Errno 2] No such file or directory: 'Real estate valuation data set.xlsx'

In [3]:
data = df.values
X = data[:,3:6]
y = data[:,-1]
print(X.shape)
print(y.shape)

(414, 3)
(414,)


In [4]:
print(X[:5])
print(y[:5])

[[ 84.87882  10.       24.98298]
 [306.5947    9.       24.98034]
 [561.9845    5.       24.98746]
 [561.9845    5.       24.98746]
 [390.5684    5.       24.97937]]
[37.9 42.2 47.3 54.8 43.1]


In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
print(X_scaled[0])

[0.00951267 1.         0.61694135]


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled,y,random_state=42,
                                                    test_size=0.25)

In [15]:
from sklearn.neighbors import KNeighborsRegressor
kNN = KNeighborsRegressor(n_neighbors=5)
kNN.fit(X_train, y_train)
y_pred = kNN.predict(X_test)

In [16]:
from sklearn.metrics import mean_absolute_error
error = mean_absolute_error(y_test,y_pred)
print(error)

5.500192307692307


In [17]:
#SVM regressor
from sklearn import svm
regr = svm.SVR()
regr.fit(X_train, y_train)

y_pred = regr.predict(X_test)


In [18]:
from sklearn.metrics import mean_absolute_error
error = mean_absolute_error(y_test,y_pred)
print(error)

6.063446355840712
